#!/usr/bin/env node

/** Build the canonical sitemap from fixed product routes and the curated registry. */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const registryPath = path.join(projectRoot, "config", "curated-books.json");
const sitemapPath = path.join(projectRoot, "public", "sitemap.xml");
const siteOrigin = "https://thestoryscrolls.com";

const rootRoutes = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/stories/alice-in-wonderland/", changefreq: "monthly", priority: "0.8" },
  {
    path: "/stories/the-wonderful-wizard-of-oz/",
    changefreq: "monthly",
    priority: "0.8",
  },
];

const productRoutes = [
  { path: "/community/", changefreq: "daily", priority: "0.7" },
  { path: "/create/", changefreq: "monthly", priority: "0.5" },
  { path: "/about/", changefreq: "monthly", priority: "0.5" },
  { path: "/privacy/", changefreq: "monthly", priority: "0.3" },
  { path: "/terms/", changefreq: "monthly", priority: "0.3" },
];

function escapeXml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

const registry = JSON.parse(await readFile(registryPath, "utf8"));
if (!Array.isArray(registry)) {
  throw new TypeError("config/curated-books.json must contain an array");
}

const slugs = registry.map((book, index) => {
  const slug = book?.slug;
  if (typeof slug !== "string" || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    throw new TypeError(`Curated registry entry ${index + 1} has an invalid slug`);
  }
  return slug;
});

if (new Set(slugs).size !== slugs.length) {
  throw new Error("config/curated-books.json contains duplicate slugs");
}

const registryRoutes = [...slugs]
  .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0))
  .map((slug) => ({
    path: `/stories/${slug}/`,
    changefreq: "monthly",
    priority: "0.8",
  }));

const routes = [...rootRoutes, ...registryRoutes, ...productRoutes];
const routePaths = routes.map((route) => route.path);
if (new Set(routePaths).size !== routePaths.length) {
  throw new Error("Sitemap routes must be unique");
}

const urlEntries = routes
  .map(
    (route) => `  <url>
    <loc>${escapeXml(new URL(route.path, siteOrigin).href)}</loc>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
  )
  .join("\n");

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs from config/curated-books.json. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

await writeFile(sitemapPath, sitemap, "utf8");
process.stdout.write(
  `Wrote public/sitemap.xml with ${routes.length} routes (${registryRoutes.length} registry books).\n`,
);
